# Generated by Django 2.1.3 on 2019-04-02 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='datesofmonth',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('weekday', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(blank=True, default='', max_length=100, null=True)),
            ],
        ),
        
    ]
