# Generated by Django 2.1.3 on 2019-04-02 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='datesofmonth',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('weekday', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(blank=True, default='', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Projectname', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Empid', models.CharField(max_length=250)),
                ('Name', models.CharField(blank=True, max_length=50)),
                ('Team', models.CharField(blank=True, default='', max_length=50)),
                ('Primarytask', models.CharField(blank=True, default='', max_length=50)),
                ('Report_date', models.DateField(null=True)),
                ('Attendence', models.CharField(default='', max_length=50)),
                ('Task', models.CharField(blank=True, choices=[('Scripting', 'Scripting'), ('Re-scripting', 'Rescripting'), ('Analysis', 'Analysis'), ('Manual', 'Manual'), ('Tool Monitoring', 'Tool Monitoring'), ('Meeting', 'Meeting'), ('URL Identification', 'URL Identification'), ('Duplicate Identification', 'Duplicate Identification'), ('Hotelcode Identification', 'Hotelcode Identification')], max_length=50)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('End_time', models.DateTimeField(blank=True, null=True)),
                ('No_hours', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, verbose_name='Number of Hours')),
                ('hold_hours', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, verbose_name='Number of Hours')),
                ('Comments', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('dtcollected', models.DateField(auto_now_add=True)),
                ('status', models.IntegerField(blank=True, default=0)),
                ('Reportstatus', models.CharField(blank=True, default='Waiting', max_length=50)),
                ('Project_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='report.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, default='', max_length=250)),
                ('EmpID', models.CharField(max_length=250)),
                ('Attitude', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('TaskInterpretation', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('TaskUnderstanding', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('Approach', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('Communication', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('Execution', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('Commitment', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('Fulfillment', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('Performance', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('Comments', models.CharField(blank=True, default='', max_length=1500)),
                ('dtcollected', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subproject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subproject_name', models.CharField(max_length=30)),
                ('Project_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('task', models.CharField(blank=True, default='', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Teamname', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='Empimage',
            field=models.ImageField(blank=True, null=True, upload_to='EmpImages/', verbose_name='EmpImages'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='Team',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='legacy_Empid',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='Empid',
            field=models.CharField(max_length=250),
        ),
        migrations.AddField(
            model_name='subproject',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.Team'),
        ),
        migrations.AddField(
            model_name='report',
            name='Subproject_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='report.Subproject'),
        ),
        migrations.AddField(
            model_name='project',
            name='Team_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.Team'),
        ),
    ]
