# Generated by Django 2.1.3 on 2019-04-02 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_auto_20190402_1425'),
    ]

    operations = [
        migrations.CreateModel(
            name='projectTask',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('task', models.CharField(blank=True, default='', max_length=100, null=True)),
            ],
        ),
    ]
