# Generated by Django 2.1.3 on 2019-04-03 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_projecttask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='Task',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
