# Generated by Django 2.2.3 on 2020-05-18 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_projecttask'),
    ]

    operations = [
        
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, default='', max_length=250)),
                ('EmpID', models.CharField(max_length=25)),
                ('legacy_Empid', models.CharField(max_length=25)),
                ('Reviewer', models.CharField(blank=True, default='', max_length=250)),
                ('Project', models.CharField(max_length=250)),
                ('Review_month', models.CharField(max_length=25)),
                ('Project_Knowledge', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('Productivity', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('Quality', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('Communication', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('Initiative', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('Reporting', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('Attendance', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('Attitude', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('Stability', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('Team_Coordination', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('Responsibility', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('Total', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('Remarks', models.CharField(blank=True, default='', max_length=1500)),
                ('dtcollected', models.DateField(auto_now_add=True)),
            ],
        ),
        
    ]
