# Generated by Django 2.1.1 on 2018-11-14 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0004_project_subproject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Empid', models.IntegerField(blank=True, default='')),
                ('Name', models.CharField(blank=True, max_length=50)),
                ('Primarytask', models.CharField(blank=True, default='', max_length=50)),
                ('Report_date', models.DateField(null=True)),
                ('Attendence', models.CharField(default='', max_length=50)),
                ('Task', models.CharField(blank=True, choices=[('Scripting', 'Scripting'), ('Re-scripting', 'Rescripting'), ('Analysis', 'Analysis'), ('Manual', 'Manual'), ('Tool Monitoring', 'Tool Monitoring'), ('Meeting', 'Meeting'), ('URL Identification', 'URL Identification'), ('Duplicate Identification', 'Duplicate Identification'), ('Hotelcode Identification', 'Hotelcode Identification')], max_length=50)),
                ('No_hours', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, verbose_name='Number of Hours')),
                ('No_count', models.IntegerField(blank=True, default=0)),
                ('Comments', models.CharField(default='', max_length=500)),
                ('dtcollected', models.DateField(auto_now_add=True)),
                ('Project_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='report.Project')),
                ('Subproject_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='report.Subproject')),
            ],
        ),
    ]
