# Generated by Django 2.2.3 on 2020-07-27 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0004_auto_20200518_1349'),
    ]

    operations = [
        
        
        
        migrations.AddField(
            model_name='customuser',
            name='Empimage',
            field=models.ImageField(blank=True, null=True, upload_to='EmpImages/', verbose_name='EmpImages'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='Empstatus',
            field=models.CharField(blank=True, default='Active', max_length=50),
        ),
        migrations.AddField(
            model_name='customuser',
            name='Team',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='legacy_Empid',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='Empid',
            field=models.CharField(max_length=250),
        ),
        
        
        
    ]
