# Generated by Django 2.1.1 on 2018-11-14 11:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0005_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='No_count',
        ),
        migrations.AddField(
            model_name='report',
            name='End_time',
            field=models.TimeField(blank=True, default=django.utils.timezone.now, verbose_name='Conversation Time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='start_time',
            field=models.TimeField(blank=True, default=django.utils.timezone.now, verbose_name='Conversation Time'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='report',
            name='Comments',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
