# Generated by Django 2.1.1 on 2018-11-14 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0006_auto_20181114_1110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='End_time',
        ),
        migrations.RemoveField(
            model_name='report',
            name='start_time',
        ),
    ]
