# Generated by Django 2.1.1 on 2018-11-14 11:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0007_auto_20181114_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='End_time',
            field=models.TimeField(blank=True, default=datetime.time(11, 26, 12, 209580), verbose_name='Conversation Time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='start_time',
            field=models.TimeField(blank=True, default=datetime.time(11, 26, 29, 939617), verbose_name='Conversation Time'),
            preserve_default=False,
        ),
    ]
