# Generated by Django 2.1.1 on 2018-11-15 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0008_auto_20181114_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='hold_hours',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, verbose_name='Number of Hours'),
        ),
    ]
