# Generated by Django 2.1.1 on 2018-11-16 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0010_auto_20181116_0649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='No_hours',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=9, verbose_name='Number of Hours'),
        ),
    ]
