# Generated by Django 2.1.1 on 2018-11-19 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0011_auto_20181116_0816'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='status',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='report',
            name='No_hours',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, verbose_name='Number of Hours'),
        ),
    ]
