# Generated by Django 2.1.1 on 2018-11-19 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0012_auto_20181119_0534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='End_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
    ]
