# Generated by Django 2.1.1 on 2018-11-19 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0013_auto_20181119_0624'),
    ]

    operations = [
        migrations.CreateModel(
            name='datesofmonth',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('weekday', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, default='', max_length=250)),
                ('EmpID', models.IntegerField(blank=True, default=0)),
                ('Attitude', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('TaskInterpretation', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('TaskUnderstanding', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('Approach', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('Communication', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('Execution', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('Commitment', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('Fulfillment', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('Performance', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('Comments', models.CharField(blank=True, default='', max_length=1500)),
                ('dtcollected', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
