# Generated by Django 2.1.1 on 2018-11-20 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0014_datesofmonth_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='End_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
