# Generated by Django 2.1.1 on 2018-11-21 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0015_auto_20181120_0844'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='Team',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
