# Generated by Django 2.1.1 on 2018-11-22 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0016_customuser_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='Team',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
