# Generated by Django 2.1.1 on 2018-11-26 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0019_report_reportstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='Empimage',
            field=models.ImageField(blank=True, upload_to='EmpImages/', verbose_name='EmpImages'),
        ),
    ]
