# Generated by Django 2.1.1 on 2018-11-26 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0020_customuser_empimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='Empimage',
            field=models.ImageField(upload_to='EmpImages/', verbose_name='EmpImages'),
        ),
    ]
