# Generated by Django 2.1.1 on 2018-12-08 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0023_designation_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='subproject',
            name='team',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='report.Team'),
            preserve_default=False,
        ),
    ]
