# Generated by Django 2.1.1 on 2018-12-11 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0025_auto_20181211_0847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='Report_date',
            field=models.DateField(null=True),
        ),
    ]
