# Generated by Django 2.1.1 on 2018-12-12 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0026_auto_20181211_0848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='No_hours',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=5, verbose_name='Number of Hours'),
        ),
        migrations.AlterField(
            model_name='report',
            name='hold_hours',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=5, verbose_name='Number of Hours'),
        ),
    ]
