# Generated by Django 2.1.1 on 2018-12-12 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0027_auto_20181212_0825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='hold_hours',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, verbose_name='Number of Hours'),
        ),
    ]
