# Generated by Django 2.1.1 on 2018-12-12 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0028_auto_20181212_0830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='No_hours',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, verbose_name='Number of Hours'),
        ),
        migrations.AlterField(
            model_name='report',
            name='hold_hours',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, verbose_name='Number of Hours'),
        ),
    ]
