# Generated by Django 2.1.1 on 2018-12-18 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0029_auto_20181212_0840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='Empid',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='EmpID',
            field=models.IntegerField(blank=True),
        ),
    ]
