# Generated by Django 2.1.1 on 2018-12-18 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0030_auto_20181218_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
