# Generated by Django 2.1.1 on 2018-12-18 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0031_auto_20181218_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
