# Generated by Django 2.1.1 on 2018-12-19 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0032_auto_20181218_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='Empid',
            field=models.IntegerField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='review',
            name='EmpID',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
