# Generated by Django 2.1.1 on 2019-01-17 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0033_auto_20181219_0607'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='legacy_Empid',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='Empid',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='report',
            name='Empid',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='review',
            name='EmpID',
            field=models.CharField(max_length=250),
        ),
    ]
