# Generated by Django 2.1.1 on 2019-04-02 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0034_auto_20190117_0532'),
    ]

    operations = [
        migrations.CreateModel(
            name='projectTask',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('task', models.CharField(blank=True, default='', max_length=100, null=True)),
            ],
        ),
    ]
